/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesignsRouteImport } from './routes/designs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignsIndexRouteImport } from './routes/designs.index'
import { Route as DesignsSlugRouteImport } from './routes/designs.$slug'

const DesignsRoute = DesignsRouteImport.update({
  id: '/designs',
  path: '/designs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsIndexRoute = DesignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DesignsRoute,
} as any)
const DesignsSlugRoute = DesignsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DesignsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/designs': typeof DesignsRouteWithChildren
  '/designs/$slug': typeof DesignsSlugRoute
  '/designs/': typeof DesignsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/designs/$slug': typeof DesignsSlugRoute
  '/designs': typeof DesignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/designs': typeof DesignsRouteWithChildren
  '/designs/$slug': typeof DesignsSlugRoute
  '/designs/': typeof DesignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/designs' | '/designs/$slug' | '/designs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/designs/$slug' | '/designs'
  id: '__root__' | '/' | '/designs' | '/designs/$slug' | '/designs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignsRoute: typeof DesignsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/designs': {
      id: '/designs'
      path: '/designs'
      fullPath: '/designs'
      preLoaderRoute: typeof DesignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs/': {
      id: '/designs/'
      path: '/'
      fullPath: '/designs/'
      preLoaderRoute: typeof DesignsIndexRouteImport
      parentRoute: typeof DesignsRoute
    }
    '/designs/$slug': {
      id: '/designs/$slug'
      path: '/$slug'
      fullPath: '/designs/$slug'
      preLoaderRoute: typeof DesignsSlugRouteImport
      parentRoute: typeof DesignsRoute
    }
  }
}

interface DesignsRouteChildren {
  DesignsSlugRoute: typeof DesignsSlugRoute
  DesignsIndexRoute: typeof DesignsIndexRoute
}

const DesignsRouteChildren: DesignsRouteChildren = {
  DesignsSlugRoute: DesignsSlugRoute,
  DesignsIndexRoute: DesignsIndexRoute,
}

const DesignsRouteWithChildren =
  DesignsRoute._addFileChildren(DesignsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignsRoute: DesignsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
